### ISSUE TITLE
Please tag release

### ISSUE THREAD

**Issue by tillea** [rvaser/logger#1]
Hi,
logger seems to be used in latest version of racon.  I'd like to update the Debian package and thus need to package logger as a separate package per Debian policy.  It would help if you could tag a production ready release.
Thanks a lot, Andreas.

**Comment by rvaser** [comment]
Will sort it out!

Best regards,
Robert

**Comment by tillea** [comment]
Any news?  Its just a `git tag ` away.

**Comment by rvaser** [comment]
Done. Sorry for the delay!

Best regards,
Robert
